import { db } from "./db"

export async function ensurePlansSeeded() {
  try {
    const count = await db.subscriptionPlan.count()
    if (count > 0) return

    console.log("Seeding default subscription plans...")

    await db.subscriptionPlan.createMany({
      data: [
        {
          name: "Gratuit",
          description: "Pour essayer la plateforme et découvrir ses fonctionnalités de base.",
          type: "GRATUIT",
          durationYears: 0,
          durationMonths: 0,
          durationDays: 7,
          durationHours: 0,
          durationMinutes: 0,
          durationSeconds: 0,
          billingPeriodType: "NONE",
          priceMonthly: 0,
          priceYearly: 0,
          paymentMethods: "Gratuit",
          maxTeams: 1,
          staffLimits: {
            ENTRAINEUR_PRINCIPAL: 1,
            ENTRAINEUR_ADJOINT: 0,
            PREPARATEUR_PHYSIQUE: 0,
            ENTRAINEUR_GARDIENS: 0,
            MEDECIN: 0,
            DIRECTEUR_SPORTIF: 0,
            SECRETAIRE_GENERAL: 0,
          },
          hasDashboard: true,
          hasPayment: true,
          hasPlanning: true,
          hasMessaging: true,
          hasPolls: false,
          hasStructure: true,
          hasStaff: true,
          hasPlayers: true,
          hasTactical: true,
          hasTrainings: true,
          hasMatches: false,
          hasInjuries: false,
          hasMedical: false,
          hasTests: false,
          hasWelfare: false,
          hasRbac: true,
          hasSupport: false,
          hasGPS: false,
          featuresList: [
            "1 seule catégorie / équipe",
            "Jusqu'à 15 profils de joueurs",
            "Planification standard d'entraînements",
            "Tableau tactique & compositions",
            "Messagerie instantanée du club",
          ],
          popular: false,
          colorTheme: "rose",
        },
        {
          name: "1 Équipe",
          description: "Idéal pour les entraîneurs individuels ou les petites académies gérant une seule équipe.",
          type: "PAYANT",
          durationYears: 0,
          durationMonths: 1,
          durationDays: 0,
          durationHours: 0,
          durationMinutes: 0,
          durationSeconds: 0,
          billingPeriodType: "BOTH",
          priceMonthly: 10000,
          priceYearly: 100000,
          paymentMethods: "CCP, BaridiMob, Virement",
          maxTeams: 1,
          staffLimits: {
            ENTRAINEUR_PRINCIPAL: 1,
            ENTRAINEUR_ADJOINT: 0,
            PREPARATEUR_PHYSIQUE: 0,
            ENTRAINEUR_GARDIENS: 0,
            MEDECIN: 1,
            DIRECTEUR_SPORTIF: 1,
            SECRETAIRE_GENERAL: 0,
          },
          hasDashboard: true,
          hasPayment: true,
          hasPlanning: true,
          hasMessaging: true,
          hasPolls: true,
          hasStructure: true,
          hasStaff: true,
          hasPlayers: true,
          hasTactical: true,
          hasTrainings: true,
          hasMatches: true,
          hasInjuries: true,
          hasMedical: true,
          hasTests: false,
          hasWelfare: false,
          hasRbac: true,
          hasSupport: true,
          hasGPS: false,
          featuresList: [
            "1 seule catégorie / équipe",
            "Jusqu'à 30 profils de joueurs",
            "Planification standard d'entraînements",
            "Fiches de performance individuelles",
            "Support technique par Email",
          ],
          popular: false,
          colorTheme: "sky",
        },
        {
          name: "Club",
          description: "Parfait pour les clubs structurés qui souhaitent centraliser la gestion de toutes leurs catégories.",
          type: "PAYANT",
          durationYears: 0,
          durationMonths: 1,
          durationDays: 0,
          durationHours: 0,
          durationMinutes: 0,
          durationSeconds: 0,
          billingPeriodType: "BOTH",
          priceMonthly: 15000,
          priceYearly: 144000,
          paymentMethods: "CCP, BaridiMob, Virement",
          maxTeams: -1, // illimité
          staffLimits: {
            ENTRAINEUR_PRINCIPAL: -1,
            ENTRAINEUR_ADJOINT: -1,
            PREPARATEUR_PHYSIQUE: -1,
            ENTRAINEUR_GARDIENS: -1,
            MEDECIN: -1,
            DIRECTEUR_SPORTIF: -1,
            SECRETAIRE_GENERAL: -1,
          },
          hasDashboard: true,
          hasPayment: true,
          hasPlanning: true,
          hasMessaging: true,
          hasPolls: true,
          hasStructure: true,
          hasStaff: true,
          hasPlayers: true,
          hasTactical: true,
          hasTrainings: true,
          hasMatches: true,
          hasInjuries: true,
          hasMedical: true,
          hasTests: false,
          hasWelfare: false,
          hasRbac: true,
          hasSupport: true,
          hasGPS: false,
          featuresList: [
            "Catégories et équipes illimitées",
            "Profils de joueurs illimités",
            "Planification d'entraînements & matchs",
            "Messagerie et sondages du club",
            "Support technique standard",
          ],
          popular: false,
          colorTheme: "indigo",
        },
        {
          name: "Professionnel",
          description: "La solution ultime pour optimiser les performances athlétiques et le suivi médical de vos équipes.",
          type: "PAYANT",
          durationYears: 0,
          durationMonths: 1,
          durationDays: 0,
          durationHours: 0,
          durationMinutes: 0,
          durationSeconds: 0,
          billingPeriodType: "BOTH",
          priceMonthly: 20000,
          priceYearly: 192000,
          paymentMethods: "CCP, BaridiMob, Virement",
          maxTeams: -1,
          staffLimits: {
            ENTRAINEUR_PRINCIPAL: -1,
            ENTRAINEUR_ADJOINT: -1,
            PREPARATEUR_PHYSIQUE: -1,
            ENTRAINEUR_GARDIENS: -1,
            MEDECIN: -1,
            DIRECTEUR_SPORTIF: -1,
            SECRETAIRE_GENERAL: -1,
          },
          hasDashboard: true,
          hasPayment: true,
          hasPlanning: true,
          hasMessaging: true,
          hasPolls: true,
          hasStructure: true,
          hasStaff: true,
          hasPlayers: true,
          hasTactical: true,
          hasTrainings: true,
          hasMatches: true,
          hasInjuries: true,
          hasMedical: true,
          hasTests: true,
          hasWelfare: true,
          hasRbac: true,
          hasSupport: true,
          hasGPS: false,
          featuresList: [
            "Toutes les fonctionnalités Club",
            "Suivi médical complet & blessures",
            "Tests physiques avancés (VMA, RPE)",
            "Fiches quotidiennes de forme (Well-being)",
            "Support prioritaire 24/7",
          ],
          popular: true,
          colorTheme: "emerald",
        },
        {
          name: "Elite",
          description: "Pour les structures de haut niveau exigeant la télémétrie GPS en temps réel et des analyses avancées.",
          type: "PAYANT",
          durationYears: 0,
          durationMonths: 1,
          durationDays: 0,
          durationHours: 0,
          durationMinutes: 0,
          durationSeconds: 0,
          billingPeriodType: "BOTH",
          priceMonthly: 25000,
          priceYearly: 240000,
          paymentMethods: "CCP, BaridiMob, Virement",
          maxTeams: -1,
          staffLimits: {
            ENTRAINEUR_PRINCIPAL: -1,
            ENTRAINEUR_ADJOINT: -1,
            PREPARATEUR_PHYSIQUE: -1,
            ENTRAINEUR_GARDIENS: -1,
            MEDECIN: -1,
            DIRECTEUR_SPORTIF: -1,
            SECRETAIRE_GENERAL: -1,
          },
          hasDashboard: true,
          hasPayment: true,
          hasPlanning: true,
          hasMessaging: true,
          hasPolls: true,
          hasStructure: true,
          hasStaff: true,
          hasPlayers: true,
          hasTactical: true,
          hasTrainings: true,
          hasMatches: true,
          hasInjuries: true,
          hasMedical: true,
          hasTests: true,
          hasWelfare: true,
          hasRbac: true,
          hasSupport: true,
          hasGPS: true,
          featuresList: [
            "Toutes les fonctionnalités Professionnel",
            "Intégration de la télémétrie GPS en direct",
            "Accès aux données physiologiques de pointe",
            "Espace Secrétaire et Directeur complet",
            "Gestionnaire de compte dédié",
          ],
          popular: false,
          colorTheme: "amber",
        },
      ],
    })

    console.log("Seeding subscription plans completed successfully!")
  } catch (error) {
    console.error("Error seeding plans:", error)
  }
}
